# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.12'

- script: python -m pip install git+https://chromium.googlesource.com/external/gyp
  displayName: 'Install gyp'

- script: ./buildMacos.sh Release
  displayName: 'make'

- script: ./smokeTestMacos.sh
  workingDirectory: .
  displayName: 'Smoke Test'

- task: PublishTestResults@2
  name: 'PublishDirectZobTests'
  inputs:
    testResultsFormat: 'JUnit'
    #testResultsFormat: VSTest
    testResultsFiles: '**/*_unittests.xml'
    #mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'GTest Results'