# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install git+https://chromium.googlesource.com/external/gyp
  displayName: 'Install gyp'

- script: ./buildMacos.sh Debug
  displayName: 'make'

- script: ./smokeTestMacos.sh
  workingDirectory: .
  displayName: 'Smoke Test'